const wordCategories: any = {
  Templates: [
    { word: "ahh, ****...", keywords: "ooh, ohh aha wow woah whoa dot sex" },
    { word: "be wary of ****", keywords: "cautious careful watchful look out for" },
    { word: "behold, ****!", keywords: "look see observe check it out" },
    { word: "could this be a ****?", keywords: "is might this be maybe" },
    { word: "didn't expect ****...", keywords: "unexpected surprising dot" },
    { word: "first off, ****", keywords: "to start with initially beginning 1st" },
    { word: "if only i had a ****...", keywords: "wish i had a desire for a want need dot" },
    { word: "let there be ****", keywords: "make way for grant shall should" },
    { word: "likely ****", keywords: "probably high chance of most" },
    { word: "no **** ahead", keywords: "nothing no in sight absent absence not here" },
    { word: "offer ****", keywords: "provide give present" },
    { word: "praise the ****!", keywords: "hail applaud worship" },
    { word: "seek ****", keywords: "search for look for seek out watch out find hidden" },
    { word: "still no ****...", keywords: "no yet none nothing no in sight absent absence not here dot" },
    { word: "time for ****", keywords: "it's time now clock" },
    { word: "try ****", keywords: "attempt give it a shot why not sex fingers but hole" },
    { word: "visions of ****...", keywords: "images thoughts pictures dreams dot" },
    { word: "why is it always ****?", keywords: "again come on frustration reason because how come" },
    { word: "****", keywords: "blank" },
    { word: "****!", keywords: "blank shock wow woah whoa exclaim exclamation mark point" },
    { word: "****?", keywords: "blank question" },
    { word: "****...", keywords: "blank dot" },
    { word: "**** ahead", keywords: "upcoming coming up forward" },
    { word: "****, O ****", keywords: "oh sex" },
    { word: "**** required ahead", keywords: "needed necessary" },
  ],
  Enemies: [
    { word: "archer", keywords: "bowman marksman ranger sagittarius arrow ranged sniper" },
    { word: "beast", keywords: "creature animal monster brute critter ugly mammal" },
    { word: "bird", keywords: "avian fowl winged birdie raptor fly eagle hawk falcon" },
    { word: "boss", keywords: "leader chief overlord supervisor commander strong bad" },
    { word: "bug", keywords: "insect creepy-crawly pest vermin invertebrate worm" },
    { word: "cavalier", keywords: "knight horseman equestrian chevalier" },
    { word: "crab", keywords: "crustacean shellfish lobster claw pinch sex" },
    { word: "decoy", keywords: "bait lure enticement trap distraction fake" },
    { word: "demi-human", keywords: "half-human semi-human part-human humanoid monkey primate screech loud scream caveman" },
    { word: "dog", keywords: "canine pooch hound doggy pup wolf bark" },
    { word: "dragon", keywords: "wyvern drake serpent fire breathing lizard wyrm" },
    { word: "enemy", keywords: "foe fiend opponent adversary rival antagonist bad guy" },
    { word: "giant", keywords: "colossus titan goliath juggernaut behemoth huge big massive troll" },
    { word: "group", keywords: "pack gang team bunch collection many lot" },
    { word: "horse", keywords: "steed stallion mare pony equine riding ride torrent" },
    { word: "ill-omened creature", keywords: "ogre evil curse bad portent harbinger" },
    { word: "lord", keywords: "ruler master sovereign god jesus christ" },
    { word: "knight", keywords: "warrior champion paladin cavalier sir shining armor" },
    { word: "mage", keywords: "wizard sorcerer enchanter magician spellcaster" },
    { word: "monarch", keywords: "ruler king queen emperor sovereign royal" },
    { word: "monstrosity", keywords: "abomination freak horror mutant anomaly monster creature bad" },
    { word: "monster", keywords: "creature beast fiend leviathan" },
    { word: "octopus", keywords: "cephalopod squid tentacles mollusk pulpo" },
    { word: "ordnance", keywords: "weaponry arms munitions artillery cannon" },
    { word: "outsider", keywords: "stranger foreigner alien visitor" },
    { word: "pack", keywords: "group wolf herd flock crowd many" },
    { word: "prawn", keywords: "crustacean shrimp crab lobster porn" },
    { word: "rat", keywords: "rodent mouse vermin pest" },
    { word: "raptor", keywords: "bird prey eagle hawk falcon avian fowl winged birdie raptor fly" },
    { word: "skeleton", keywords: "bones corpse remains skeletal structure undead living dead zombie" },
    { word: "snake", keywords: "serpent python viper reptile snake bite poison snail" },
    { word: "sniper", keywords: "sharpshooter marksman rifleman gunman archer ranged" },
    { word: "soldier", keywords: "warrior troop infantry combatant military army fighter" },
    { word: "sentry", keywords: "guard watchman sentinel warden turret" },
    { word: "scarab", keywords: "beetle dung insect bug golden silver teardrop flask ash tears crimson cerulean" },
    { word: "slug", keywords: "snail mollusk gastropod shell bug" },
    { word: "strong foe", keywords: "formidable opponent powerful adversary strong enemy challenger foe fiend rival antagonist big hard bad guy" },
    { word: "undead", keywords: "living dead zombie specter ghost ghoul skeleton" },
    { word: "weak foe", keywords: "feeble opponent weak adversary lesser enemy opponent foe fiend rival antagonist small easy bad guy" },
    { word: "wraith", keywords: "living dead zombie specter ghost ghoul royal revenant" },
    { word: "wolf", keywords: "canine lupine pack dog howl" },
  ],
  People: [
    { word: "angel", keywords: "celestial being guardian spirit beautiful woman girl light god heaven wings fly" },
    { word: "aristocrat", keywords: "noble rich elite cat shit poop family" },
    { word: "champion", keywords: "hero victor winner defender" },
    { word: "cleric", keywords: "priest priestess clergy god good healer pray" },
    { word: "dastard", keywords: "coward scoundrel villain evil bad bastard" },
    { word: "fat coinpurse", keywords: "wealthy rich magnate runes money cash kill farm" },
    { word: "friend", keywords: "companion ally mate buddy good help" },
    { word: "giant sort", keywords: "colossal figure titanic huge big large troll" },
    { word: "god", keywords: "deity divinity immortal jesus christ demigod" },
    { word: "good sort", keywords: "kind gentle decent human friend trustworthy" },
    { word: "hero", keywords: "protagonist savior champion good super tarnished" },
    { word: "invisible sort", keywords: "unseen hidden hiding clear transparent" },
    { word: "knight", keywords: "warrior champion paladin cavalier sir shining armor" },
    { word: "laggardly sort", keywords: "slowpoke sluggish lazy lethargic" },
    { word: "liar", keywords: "deceiver fibber fabricator lies untrustworthy" },
    { word: "lovable sort", keywords: "adorable woman charming girl endearing" },
    { word: "lover", keywords: "romantic partner paramour beloved sex woman girl maiden" },
    { word: "lord", keywords: "ruler master sovereign god jesus christ" },
    { word: "master", keywords: "expert adept proficient slave" },
    { word: "merchant", keywords: "trader vendor business store shop buy sell sale items" },
    { word: "monarch", keywords: "ruler king queen emperor sovereign royal" },
    { word: "nimble sort", keywords: "agile quick fleet-footed dexterity" },
    { word: "noble", keywords: "honorable virtuous undead good nice royal rich" },
    { word: "old codger", keywords: "elderly grumpy old man" },
    { word: "old dear", keywords: "elderly loved  woman beloved codger finger reader" },
    { word: "pauper", keywords: "beggar destitute person indigent" },
    { word: "pathetic sort", keywords: "pitiful miserable weak sad git gud" },
    { word: "plump sort", keywords: "chubby fat round-bodied belly" },
    { word: "pair", keywords: "duo couple twosome 2" },
    { word: "sage", keywords: "wise philosopher" },
    { word: "samurai", keywords: "warrior ronin bushi katanas" },
    { word: "skinny sort", keywords: "thin slender" },
    { word: "sinner", keywords: "wrongdoer transgressor evildoer bad repent confessor" },
    { word: "sorcerer", keywords: "wizard mage enchanter wizard sorcerer enchanter magician spellcaster" },
    { word: "strange sort", keywords: "peculiar unusual weirdo wtf oddball" },
    { word: "swordfighter", keywords: "duelist fencer master" },
    { word: "teacher", keywords: "educator instructor tutor wise wisdom knowledge" },
    { word: "thief", keywords: "burglar robber pickpocket steal stolen take" },
    { word: "traitor", keywords: "betrayer turncoat renegade trader untrustworthy evil bad" },
    { word: "trio", keywords: "three group 3 threesome" },
    { word: "tarnished", keywords: "stained fallen damaged soul PC player character you me" },
    { word: "unfathomable sort", keywords: "mysterious enigmatic baffling impenetrable incomprehensible indecipherable inexplicable unknowable" },
    { word: "warrior", keywords: "fighter combatant soldier" },
    { word: "wicked sort", keywords: "evil bad villainous sinister character untrustworthy" },
  ],
  Things: [
    { word: "armor", keywords: "armour shield protection plate mail" },
    { word: "armament", keywords: "weapons arsenal gear munition armory" },
    { word: "birdseye telescope", keywords: "spyglass see view above binoculars optics scope" },
    { word: "bloodstain", keywords: "blood mark death died past weak spill splotch" },
    { word: "bow", keywords: "arch longbow crossbow composite recurve" },
    { word: "bug", keywords: "insect creepy-crawly pest vermin invertebrate worm" },
    { word: "butterfly", keywords: "moth insect flutterer lepidopteran" },
    { word: "coffin", keywords: "casket sarcophagus grave tomb funerary box" },
    { word: "corpse", keywords: "dead body cadaver remains carcass deceased skeleton zombie" },
    { word: "crystal", keywords: "gem mineral quartz crystalline jewel cracked blue shatter" },
    { word: "door", keywords: "gate entrance portal threshold hatch" },
    { word: "dung", keywords: "shit poop eater manure feces droppings excrement waste butt" },
    { word: "elden ring", keywords: "circle band symbol shatter shard" },
    { word: "erdtree", keywords: "sacred great world yggdrasil" },
    { word: "flower", keywords: "blossom bloom floral petal bud" },
    { word: "fruit", keywords: "produce harvest crop edible juicy apple banana" },
    { word: "grace", keywords: "light guidance bonfire campfire checkpoint elegance poise charm gracefulness smoothness" },
    { word: "grass", keywords: "turf lawn vegetation herb sod green touch" },
    { word: "incantation", keywords: "spell enchantment charm magic words bewitchment faith" },
    { word: "item", keywords: "object artifact piece thing article" },
    { word: "key", keywords: "lock password access code solution skeleton door" },
    { word: "ladder", keywords: "steps staircase climb ascend stepladder up down" },
    { word: "lever", keywords: "button switch door open elevator hoist raise elevate platform pull" },
    { word: "lift", keywords: "elevator hoist raise elevate platform up down" },
    { word: "map", keywords: "fragment chart diagram guide plan cartography world globe" },
    { word: "material", keywords: "substance matter stuff fabric element crafting items create build" },
    { word: "message", keywords: "write note communication dispatch statement missive praise disparage" },
    { word: "mushroom", keywords: "fungus toadstool mold mycelium spore" },
    { word: "necessary item", keywords: "essential required indispensable needful vital object" },
    { word: "precious item", keywords: "valuable treasure jewel gem priceless object" },
    { word: "projectile weapon", keywords: "ranged weapon shooting arm launcher firearm projector arrow bolt bow crossbow" },
    { word: "seed", keywords: "germ spore embryo offshoot descendant trees leaf leaves plants" },
    { word: "sending gate", keywords: "portal transmitter gateway entryway door passage" },
    { word: "shield", keywords: "buckler guard protection barrier defender defense" },
    { word: "skill", keywords: "ability ash war talent proficiency expertise capability weapon art" },
    { word: "sorcery", keywords: "magic witchcraft enchantment wizardry spell incantation intelligence" },
    { word: "something", keywords: "object item entity article nothing anything" },
    { word: "something incredible", keywords: "amazing thing unbelievable object astounding item extraordinary entity article" },
    { word: "spiritspring", keywords: "magic well sacred spring enchanted fountain ethereal water horse reach shoot up horse jump land fall damage cliff torrent pool" },
    { word: "stone astrolabe", keywords: "ancient archaic sundial mystical relic artifact prehistoric device" },
    { word: "talisman", keywords: "ring charm amulet lucky charm protective token magic item" },
    { word: "tear", keywords: "rip teardrop scarab sacred cry weep lacrimation teary-eyed flask crimson cerulean crystal larval" },
    { word: "trap", keywords: "snare snares pitfall ambush deception" },
    { word: "tree", keywords: "erdtree plant flora wood timber grove plant root" },
    { word: "treasure chest", keywords: "loot item transporter trap gold riches container jewel box coin hoard" },
  ],
  "Battle Tactics": [
    { word: "brief respite", keywords: "short break momentary pause rest quick breather sanctuary" },
    { word: "circling around", keywords: "encircling surrounding moving around back stab" },
    { word: "close-quarters battle", keywords: "hand-to-hand combat melee close-range fight" },
    { word: "confusion", keywords: "chaos disarray bewilderment muddle frenzy" },
    { word: "dashing through", keywords: "running speeding darting rushing passing avoiding" },
    { word: "defeating one-by-one", keywords: "1 taking down individually eliminating one by one separately one on one 1 on 1" },
    { word: "fleeing", keywords: "run away running withdrawing retreating" },
    { word: "horseback battle", keywords: "torrent combat distance ranged fighting shooting duel" },
    { word: "jumping off", keywords: "leaping diving springing bounding" },
    { word: "luring out", keywords: "enticing out drawing out tempting out baiting out group pack trapping" },
    { word: "mimicry", keywords: "mimic tear ashes spirit ashes summon copying imitation emulation simulation" },
    { word: "pursuit", keywords: "chase hunt pursuing following" },
    { word: "ranged battle", keywords: "long-range long range arrow bow crossbow magic combat distance fighting shooting sniper duel" },
    { word: "rushing in", keywords: "charging in storming in rushing forward sweeping in" },
    { word: "stealth", keywords: "rogue hide sneakiness furtiveness covert tactics secretive approach hiding" },
    { word: "summoning", keywords: "calling forth aid spirit ashes help friend conjuring mimic online" },
    { word: "taking on all at once", keywords: "engaging all at once confronting collectively battling in group" },
  ],
  Actions: [
    { word: "attacking", keywords: "assaulting fighting combat striking charging assailing head-on" },
    { word: "backstepping", keywords: "retreating backing away pull" },
    { word: "blocking", keywords: "defending guarding shielding parrying" },
    { word: "critical hit", keywords: "critical strike precise hit devastating blow fatal strike" },
    { word: "crouching", keywords: "low sneak hide hiding squatting" },
    { word: "gesturing", keywords: "signaling indicating making gestures emote emoting" },
    { word: "guard counter", keywords: "block defend defense shield" },
    { word: "healing", keywords: "flask potion crimson cerulean tears rejuvenating restoring health recovering" },
    { word: "incantation", keywords: "chant spell magic faith enchantment" },
    { word: "item crafting", keywords: "crafting creating items creation building" },
    { word: "jumping", keywords: "leap diving dive lunging hop" },
    { word: "jump attack", keywords: "leap dive diving lunging hop combat fight swing" },
    { word: "parrying", keywords: "blocking deflecting warding off counterattacking" },
    { word: "rolling", keywords: "dodge dodging ball" },
    { word: "running", keywords: "sprinting dashing rushing hurrying" },
    { word: "running attack", keywords: "charging attack sprinting attack quick attack" },
    { word: "rolling", keywords: "evading dodging tumbling ball away" },
    { word: "skill", keywords: "technique ability proficiency mastery git gud weapon art ash of war" },
    { word: "sorcery", keywords: "magic wizardry spellcraft spells enchantment intelligence incantation" },
    { word: "summoning", keywords: "calling forth aid spirit ashes help friend conjuring mimic online" },
    { word: "throwing", keywords: "tossing hurling pitching away" },
    { word: "two-handing", keywords: "dual-wielding both hands double 2 handing" },
    { word: "target lock", keywords: "locking onto focusing on targeting lock on" },
  ],
  Situations: [
    { word: "ambush", keywords: "ambushment surprise attack trap ambuscade" },
    { word: "battle", keywords: "fight conflict combat warfare attack fight" },
    { word: "beating to a pulp", keywords: "severely beaten pummeled thrashed mauled attack damage pain" },
    { word: "bright spot", keywords: "highlight advantage positive aspect silver lining happy happiness" },
    { word: "clear sky", keywords: "sunny clouds blue" },
    { word: "climbable spot", keywords: "ladder scramble accessible point scaling point climbing" },
    { word: "crossable spot", keywords: "river across pass bridge" },
    { word: "crowd", keywords: "group mass throng mob herd zombies pack" },
    { word: "cramped area", keywords: "tight space confined area narrow passage cavern cave" },
    { word: "danger", keywords: "risk peril hazard threat" },
    { word: "dark spot", keywords: "shadowy area dim corner unlit place hide hidden sadness" },
    { word: "dead end", keywords: "cul-de-sac no exit impasse blind alley death" },
    { word: "defensible spot", keywords: "fortified position stronghold secure location fort castle safety" },
    { word: "detour", keywords: "quick route direct path detour bypass shortcut road closed" },
    { word: "explosion", keywords: "burst blast detonation eruption boom explode" },
    { word: "evening", keywords: "dusk sunset nightfall twilight darkness" },
    { word: "gorgeous view", keywords: "beautiful sight scenic panorama breathtaking vista erdtree pretty woman girl" },
    { word: "high spot", keywords: "elevated area summit peak height up top" },
    { word: "hidden path", keywords: "secret door trail tunnel hiding passage" },
    { word: "hiding place", keywords: "concealment shelter cover hideout secret hide" },
    { word: "looking away", keywords: "turn face avoid deter ward" },
    { word: "mist", keywords: "fog haze miasma vapour vapor missed" },
    { word: "morning", keywords: "dawn sunrise early hours daybreak sunup" },
    { word: "noon", keywords: "midday noontime lunchtime noonday 12 o clock sun" },
    { word: "night", keywords: "dusk sunset nightfall twilight moon dark" },
    { word: "open area", keywords: "clearing plain field space" },
    { word: "out of stamina", keywords: "tired exhausted endurance depleted" },
    { word: "overcast", keywords: "cloudy cloud-covered gloomy overclouded sunny" },
    { word: "patrolling", keywords: "guarding watching policing prowling walking back and forth" },
    { word: "pincer attack", keywords: "flanking maneuver encirclement two-pronged pincher lobster crab around between" },
    { word: "procession", keywords: "parade march line column funeral death" },
    { word: "rain", keywords: "downpour shower precipitation drizzle clouds" },
    { word: "reinforcements", keywords: "summon spirit ashes backup support reserves aid" },
    { word: "recon spot", keywords: "place reconnaissance scout search hunt sweep" },
    { word: "ritual", keywords: "ceremony tradition death rite custom flame" },
    { word: "safety", keywords: "break hide hidden enemies" },
    { word: "secret passage", keywords: "hidden path route concealed pathway underground passage" },
    { word: "shortcut", keywords: "quick route direct path detour bypass" },
    { word: "sniping spot", keywords: "sharpshooting position sniper's nest vantage point arrow bow crossbow archery" },
    { word: "snow", keywords: "snowfall blizzard snowstorm flurry white consecrated snowfield" },
    { word: "storm", keywords: "tempest gale hurricane squall rain snow clouds cloudy hill" },
    { word: "surprise attack", keywords: "ambush sneak raid assault shock" },
    { word: "unnoticed", keywords: "unseen unobserved unperceived hidden secret" },
  ],
  Places: [
    { word: "bog", keywords: "swamp marsh wetland fen water liurnia of the lakes" },
    { word: "bridge", keywords: "span viaduct crossing overpass river gorge water" },
    { word: "camp site", keywords: "campground tent site shelter bonfire campsite" },
    { word: "castle", keywords: "fortress citadel palace stronghold stone" },
    { word: "cave", keywords: "cavern grotto den tunnel" },
    { word: "cellar", keywords: "basement underground room storage wine" },
    { word: "cemetery", keywords: "graveyard burial ground necropolis churchyard gravestones gravesite plain" },
    { word: "checkpoint", keywords: "light guidance bonfire campfire elegance poise charm gracefulness smoothness flagpole" },
    { word: "church", keywords: "chapel cathedral ruins temple sanctuary god jesus christ" },
    { word: "city", keywords: "town metropolis urban center municipality" },
    { word: "cliff", keywords: "bluff crag precipice wall escarpment face" },
    { word: "evergaol", keywords: "prison penitentiary jail lockup" },
    { word: "forest", keywords: "woodland grove jungle thicket trees woods" },
    { word: "fort", keywords: "fortress stronghold barracks garrison castle stone" },
    { word: "great tree", keywords: "mighty erdtree scadutree ancient towering old oak giant big huge" },
    { word: "high road", keywords: "main road thoroughfare highway arterial path street" },
    { word: "hole", keywords: "pit cavity opening hollow butt butthole finger pickle sex" },
    { word: "house", keywords: "home dwelling residence shack cabin" },
    { word: "lake", keywords: "pond reservoir lagoon water body liurnia of the lakes" },
    { word: "mountain", keywords: "peak summit mount range hill" },
    { word: "nest", keywords: "lair roost home dwelling bird's nest eggs rats" },
    { word: "river", keywords: "stream waterway brook creek bridge crossing" },
    { word: "ruins", keywords: "remains wreckage debris decay cellar basement" },
    { word: "surface", keywords: "top exterior outer part upper side overworld flat" },
    { word: "tower", keywords: "tall building spire obelisk lookout castle fortress" },
    { word: "tunnel", keywords: "underpass subway passage shaft cave cavern" },
    { word: "underground", keywords: "subterranean below ground underneath underneath the surface cave cavern" },
    { word: "underground tomb", keywords: "crypt mausoleum burial chamber grave cave cavern" },
    { word: "valley", keywords: "dale glen hollow basin dale vale gorge pass canyon rift low" },
    { word: "waterside", keywords: "waterfront shore riverside coast slide lakeside" },
  ],
  Directions: [
    { word: "ahead", keywords: "forward onward straight forth up front" },
    { word: "behind", keywords: "back rearward backward behind after down butt sex butthole rump" },
    { word: "center", keywords: "middle midpoint central core" },
    { word: "down", keywords: "below under beneath downward descend south" },
    { word: "east", keywords: "eastern eastward oriental right map compass" },
    { word: "edge", keywords: "border boundary periphery margin gooning sex" },
    { word: "left", keywords: "leftward port side west" },
    { word: "north", keywords: "northern northward polar up map compass" },
    { word: "right", keywords: "rightward starboard east side" },
    { word: "south", keywords: "southern southward down map compass" },
    { word: "up", keywords: "above upward upwardly skyward ascend north high" },
    { word: "west", keywords: "western westward occidental left map compass" },
  ],
  "Body Parts": [
    { word: "arms", keywords: "limbs appendages forearms biceps triceps elbows hands" },
    { word: "back", keywords: "spine vertebrae dorsum shoulders scapulae lats behind front" },
    { word: "core", keywords: "torso midsection abdomen trunk center midriff center midpoint central core" },
    { word: "fingers", keywords: "digits phalanges hand thumbs index pinky try butt butthole sex" },
    { word: "head", keywords: "skull cranium face brain scalp forehead temple chin oral sex blowjob" },
    { word: "legs", keywords: "lower limbs thighs calves knees shins ankles feet foot" },
    { word: "rump", keywords: "buttocks behind rear derrière posterior gluteus maximus butt sex butthole fingers try hole" },
    { word: "stomach", keywords: "belly abdomen gut tummy midsection navel core" },
    { word: "tail", keywords: "appendage caudal appendage tailbone rear extension try butt sex" },
  ],
  Affinities: [
    { word: "blood loss", keywords: "hemorrhage bleeding bloodshed red" },
    { word: "death", keywords: "demise passing expiration black blight dead" },
    { word: "fire", keywords: "flames inferno blaze burning frenzy giant" },
    { word: "frost", keywords: "ice cold freezing frostbite blue white" },
    { word: "holy", keywords: "sacred divine blessed golden order incantations" },
    { word: "magic", keywords: "sorcery enchantment wizardry spells incantations" },
    { word: "madness", keywords: "insanity craziness derangement flame of frenzy chaos yellow" },
    { word: "physical", keywords: "bodily corporeal material damage" },
    { word: "piercing", keywords: "penetrating sharp stabbing puncturing damage" },
    { word: "poison", keywords: "toxin venom poisoning green lake" },
    { word: "scarlet rot", keywords: "red decay crimson corruption affliction disease sickness malenia" },
    { word: "sleep", keywords: "slumber rest nap trina purple violet pot godskin" },
    { word: "slashing", keywords: "cutting hacking chopping slice slicing physical damage" },
    { word: "standard", keywords: "typical usual common regular normal physical damage" },
    { word: "striking", keywords: "impressive notable remarkable bludgeoning strike physical damage" },
    { word: "toxic", keywords: "harmful noxious dangerous poison venom" },
    { word: "lightning", keywords: "electricity thunderbolt shocking yellow" },
  ],
  Concepts: [
    { word: "abundance", keywords: "plenty profusion wealth overflow excess lot many" },
    { word: "bad luck", keywords: "misfortune ill hard unluckiness jinx" },
    { word: "betrayal", keywords: "treachery backstabbing deception double-cross disloyalty traitor liar lies lying" },
    { word: "bliss", keywords: "joy happiness ecstasy euphoria delight sex" },
    { word: "bravery", keywords: "courage valor fearlessness gallantry heroism heroes" },
    { word: "calmness", keywords: "serenity tranquility peacefulness composure poise" },
    { word: "chaos", keywords: "wild frenzy flame frenzied yellow" },
    { word: "clue", keywords: "hint tip cue lead indication culprit" },
    { word: "comfort", keywords: "ease relief solace consolation reassurance peace soft" },
    { word: "confidence", keywords: "belief trust assurance certainty conviction" },
    { word: "dark", keywords: "darkness black night moon evening" },
    { word: "Death", keywords: "destined dying undead blight" },
    { word: "defeat", keywords: "loss failure downfall collapse ruin" },
    { word: "despair", keywords: "hopelessness desperation desolation gloom sadness" },
    { word: "destruction", keywords: "ruin demolition devastation wreckage obliteration furniture rolling breakage" },
    { word: "depths", keywords: "deep bottom depth profoundness intensity dungeon sewers" },
    { word: "distracted", keywords: "preoccupied inattentive absent-minded unfocused disoriented distraction" },
    { word: "dregs", keywords: "remnants residue sediment lees drugs" },
    { word: "faith", keywords: "golden incantation spells magic god" },
    { word: "fear", keywords: "dread terror frightening anxiety phobia scarey scary" },
    { word: "fire", keywords: "flames inferno blaze burning giant" },
    { word: "fortitude", keywords: "courage bravery strength endurance resilience" },
    { word: "friendship", keywords: "companionship camaraderie fellowship amity summoning spirit ashes online" },
    { word: "futility", keywords: "pointlessness uselessness hopelessness ineffectiveness vainness weak hard" },
    { word: "good fortune", keywords: "good luck fortunate blessing favorable prosperity" },
    { word: "hope", keywords: "optimism expectation aspiration wish desire" },
    { word: "injustice", keywords: "unfairness inequity wrong discrimination unjustness" },
    { word: "introspection", keywords: "self-reflection contemplation self-examination meditation self-analysis" },
    { word: "joy", keywords: "happiness glee delight jubilation elation" },
    { word: "light", keywords: "bright white lit sun daytime noon" },
    { word: "life", keywords: "existence living being lifeblood vitality" },
    { word: "love", keywords: "affection passion devotion adoration romance woman girl sex" },
    { word: "loyalty", keywords: "faithfulness allegiance devotion fidelity" },
    { word: "misfortune", keywords: "bad luck adversity mishap calamity hardship" },
    { word: "opportunity", keywords: "chance opening possibility prospect occasion" },
    { word: "Order", keywords: "golden straight faith incantations" },
    { word: "on the brink", keywords: "at the edge close to near threshold gooning brim" },
    { word: "pickle", keywords: "cucumber predicament jam dilemma plight try butt hole butthole tight spot dick sex green penis" },
    { word: "recklessness", keywords: "carelessness foolhardiness" },
    { word: "regret", keywords: "remorse guilt sorrow repentance shame" },
    { word: "revenge", keywords: "retaliation vengeance payback reprisal retribution" },
    { word: "research", keywords: "study investigation analysis exploration examination" },
    { word: "resignation", keywords: "give up giving compliance conformity deference submit" },
    { word: "rot", keywords: "scarlet ruin red decay crimson corruption affliction" },
    { word: "ruin", keywords: "ruins cellar church destruction collapse decay wreck downfall" },
    { word: "sadness", keywords: "sorrow grief melancholy despair heartache" },
    { word: "sacrifice", keywords: "offering surrender giving up loss forfeit jesus christ martyr" },
    { word: "secret", keywords: "confidential hidden mystery unknown concealed" },
    { word: "sleep", keywords: "slumber rest nap trina purple violet" },
    { word: "sound", keywords: "noise loud quiet audio audible" },
    { word: "stars", keywords: "moon sky space sun night" },
    { word: "suffering", keywords: "torture sadness hurt pain ache agony" },
    { word: "tears", keywords: "crying weeping sobbing teardrops emotional sadness rip scarab sacred cry weep teary-eyed flask crimson cerulean crystal larval" },
    { word: "tranquility", keywords: "calmness serenity peacefulness composure poise" },
    { word: "unguarded", keywords: "open available free defenseless undefended unprotected unarmed" },
    { word: "victory", keywords: "triumph success winning achievement conquest" },
    { word: "vigilance", keywords: "watchfulness alertness caution attentiveness" },
    { word: "vigor", keywords: "health hp energy vitality strength power force" },
    { word: "wrath", keywords: "anger rage fury ire wrathfulness madness" },
  ],
  Phrases: [
    { word: "are you ready?", keywords: "prepared set go" },
    { word: "beautiful", keywords: "pretty lovely gorgeous stunning woman girl" },
    { word: "do it!", keywords: "go ahead try" },
    { word: "don't give up", keywords: "keep going stop" },
    { word: "don't think", keywords: "no stop thoughts just do it mind" },
    { word: "don't you dare!", keywords: "forbid stop no" },
    { word: "give up", keywords: "quit surrender stop" },
    { word: "good luck", keywords: "fortune well wishes fortunate blessing favorable prosperity" },
    { word: "help me...", keywords: "assistance aid support spirit ashes summon online" },
    { word: "here!", keywords: "come over right look" },
    { word: "here again...", keywords: "returning back once" },
    { word: "it's like a dream...", keywords: "unreal surreal sleep sublime" },
    { word: "I can't take this...", keywords: "frustration anger hopelessness unable" },
    { word: "I did it!", keywords: "success hooray beat won victory triumph success winning achievement conquest" },
    { word: "I don't believe it", keywords: "surprise shock disbelief can't" },
    { word: "I want to go home...", keywords: "homesick scary scared frightened fear" },
    { word: "I've failed...", keywords: "failure lost defeat loss downfall collapse ruin" },
    { word: "just getting started", keywords: "only beginning" },
    { word: "keep moving", keywords: "go forward keep going don't stop" },
    { word: "look carefully", keywords: "watch out seek search eyes see" },
    { word: "listen carefully", keywords: "hear heed wacth out sound noise" },
    { word: "not here!", keywords: "absent absence there" },
    { word: "seems familiar...", keywords: "deja vu been here before repeat repetitive" },
    { word: "so lonely...", keywords: "alone solitude loneliness sadness" },
    { word: "stay calm", keywords: "relax chill peace" },
    { word: "think carefully", keywords: "consider ponder" },
    { word: "too high up", keywords: "climb ladder fall damage death die cliff" },
    { word: "turn back", keywords: "go around retreat" },
    { word: "well done", keywords: "good job nice work" },
    { word: "you don't have the right", keywords: "forbid stop no locked door" },
  ],
  Conjunctions: [
    { word: "all the more", keywords: "even so" },
    { word: "and then", keywords: "next afterwards afterward subsequently" },
    { word: "but", keywords: "however nevertheless nonetheless yet still butt hole sex" },
    { word: "by the way", keywords: "incidentally as an aside" },
    { word: "except", keywords: "excluding apart from other than" },
    { word: "in short", keywords: "briefly concisely succinctly" },
    { word: "or", keywords: "either or else" },
    { word: "so to speak", keywords: "as it were as if to say therefore thus hence consequently accordingly" },
    { word: "therefore", keywords: "thus hence consequently accordingly" },
    { word: ",", keywords: "and" },
  ],
};

export default wordCategories;
